### PR TITLE
add craft night, change some words, and make calendar "importable"

### PR DESCRIPTION
**Pull request by alifeee**
some updates to website, including:

- add craft night (it has now run for 14 consecutive weeks, since April 24th 2024)
- add some words to clarify that people can visit prospectively without becoming a member (I have heard some confusion over this)
- move calendar to `_includes` folder, so that it can be included on multiple pages with `{% include calendar.md %}`, and will stay up to date on those pages if changed

Please see the changes live on <http://shhm.alifeee.co.uk/>, or the comparison images here (see the file diff for a better idea of what has changed)

## `/` - current

image

## `/` - new

image

## `/calendar/` - current

image

## `/calendar/` - new

image

## `/joining/` - current

image

## `/joining/` - new

image

### CODE REVIEW

**Comment by LouiseMcMahon** [comment]
Looks good but could we remove the emojis and the (craft night). It looks a bit odd if the other nights aren’t specific and I don’t want to limit prospective members who may not come down that night if it’s not crafts they do.

Emojis are also a bit problematic for older devices and screen readers plus it looks a bit unprofessional in my opinion.

**Comment by LouiseMcMahon** [comment]
I don’t see any issues on mobile (chrome IPhone 14)

**Comment by alifeee** [comment]
I have removed the emoji

Here are some experiments with different looks

image

I have left it as the first one. Again, see on <http://shhm.alifeee.co.uk/>

> I don’t want to limit prospective members who may not come down that night if it’s not crafts they do.

I apologise for my directness, but I do not think this will happen at all. Thanks.

**Comment by alifeee** [comment]
also, thanks for testing on mobile. I have also done so. 

thusly, removing draft status :)

**Review by neilzilla — APPROVED** [review]
lgtm, all makes sense.

**Review by neilzilla — DISMISSED** [review]
Still looks good to me

**Comment by LouiseMcMahon** [comment]
@alifeee, The trustees, have suggested the wording `(Open night with craft focus)`

**Comment by LouiseMcMahon** [comment]
Oh and can we update it to the 2 weeks were not running wednesday.

**Comment by alifeee** [comment]
hi @LouiseMcMahon thanks for the review

your comments seem to me to reference the old suggestions, i.e., the addition of "`- Wednesday 6pm - 9pm (craft night)`".

This is no longer how this change is formatted. For example, I have already added a change to clarify that open night with craft focus is running only twice a month.

You can see the current suggestion on <http://shhm.alifeee.co.uk/> or in the screenshots at the top of this PR.

If you already saw the updated suggestion, then I misunderstand your request. Could you clarify which section you desire to be changed ?

thanks

**Review by LouiseMcMahon — APPROVED** [review]

**Pull request merged**
