### PR TITLE
Update workflows to be faster + more recent

### PR DESCRIPTION
**Pull request by alifeee**
Current workflows take *far* too long to run. The latest is

https://github.com/sheffieldhackspace/Public-Website/actions/runs/8287118405

which took 7 minutes.

image

The build test also takes several minutes.

Also, the action used (`helaili/jekyll-action`) is [deprecated](https://github.com/helaili/jekyll-action).

It is recommended to replace this with the GitHub Action for creating a page. See [guidance here](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow)

The workflows introduced in this PR are much faster, making it much less annoying to develop. They also are in-line with the recommendations. For example, here are some workflows from my fork:

### test

https://github.com/alifeee/Public-Website/actions/runs/8660606381

image

### deploy

https://github.com/alifeee/Public-Website/actions/runs/8660613710

image

This may also require the sources setting to be changed under [pages settings](https://github.com/sheffieldhackspace/Public-Website/settings/pages). Or it may update automatically.

image

### CODE REVIEW

**Review by LouiseMcMahon — APPROVED** [review]
Looks good, thanks!

**Comment by alifeee** [comment]
I will merge. let's see how it goes... ;]

**Comment by alifeee** [comment]
mm, yes. it looks like the sources setting must be changed (see above) to allow the workflow to complete

failed run:

https://github.com/sheffieldhackspace/Public-Website/actions/runs/9801071365/job/27063865356

image

**Comment by LouiseMcMahon** [comment]
Thats fixed now, just manually triggered a build https://github.com/sheffieldhackspace/Public-Website/actions/runs/9805559436

**Comment by alifeee** [comment]
lovely stuff. thanx!

**Pull request merged**
