### PR TITLE
add fonts to readme

### PR DESCRIPTION
**Pull request by alifeee**
preview

image

### CODE REVIEW

**Comment by alifeee** [comment]
image

**Review by LouiseMcMahon — APPROVED** [review]

**Comment by LouiseMcMahon** [comment]
Can i be a pain and ask you to rebase the branch on main rather than merging main into it. Things get weird if you merge main in then try and merge it back to main especially with squashes

**Review by LouiseMcMahon — CHANGES_REQUESTED** [review]
im going to be a pain and ask you to rebase the branch on main rather than merging main into it. Things get weird if you merge main in then try and merge it back to main especially with squashes

**Comment by alifeee** [comment]
> im going to be a pain and ask you to rebase the branch on main rather than merging main into it. Things get weird if you merge main in then try and merge it back to main especially with squashes

instead of this I have created a new PR -> #66 

thanks

**Pull request closed without merging**
